### PR TITLE
Added implementation of call_once and once_flag

### PR DESCRIPTION
**Pull request by cvtsi2sd**
As per MR title; this implementation was discussed over https://codereview.stackexchange.com/q/117468/41702 and should be good.

### CODE REVIEW

**Comment by alxvasilev** [comment]
It seems you have gone to great length to avoid the missing constexpr-ness of std::mutex. But, as noted in the above stackexchange thread, the std::mutex constructor is actually constexpr. It just seems that the original gthread header does not conform to that in case the pthread static mutex initialization macro PTHREAD_MUTEX_INITIALIZER is not defined.
Look at:
https://www.unvanquished.net/~modi/code/include/c++/4.9/mutex.html#123

I have not (yet) confirmed that the simpler implementation actually works, but if it does, I would rather accept the simpler implementation posted in the stackexchange thread.

**Comment by alxvasilev** [comment]
Confirmed - std::mutex constructor should be constexpr, for which it was necessary to make the ctor of the _NonrecursiveMutex mixin also constexpr. I have also added a simple test for call_once(). Hence, I am closing this PR.

**Comment by cvtsi2sd** [comment]
There's something I'm missing... how can the `_nonrecursiveMutex<recursive_mutex>` be `constexpr` if `recursive_mutex` constructor is *not* `constexpr` (and cannot be made such, as it needs to call `InitializeCriticalSection`)?

**Comment by alxvasilev** [comment]
I believe constexpr in this context means that a mutex variable can be used during static initialization,, not during compile time (it doesn't make sense to use a mutex at compile time). Here is to the doc in cppreference:
```
Notes
Because the default constructor is constexpr, static mutexes are initialized as part of static non-local initialization, before any dynamic non-local initialization begins. This makes it safe to lock a mutex in a constructor of any static object.
```

**Comment by cvtsi2sd** [comment]
Of course you cannot use a mutex at compile time, but the idea is that its "initial" memory content has to be determined at compile time; as I always understood it, a `constexpr` constructor means that the underlying storage of an object will be determined at compile time, and thus it will be already in constructed state the very moment the `.data` section of the executable image is mapped in memory from disk.

The idea is that, if the mutex initialization doesn't require to actually *do* anything, it's ready to be used  the moment any code of the executable start to run, in particular when dynamic initialization of static-storage-duration objects happens. If this isn't the case and initializing a mutex requires to "really" run some code, mutex initialization is subject to the static order of initialization fiasco as any other static-storage-duration variable, thus defeating the very point of the passage you quoted.

That being said, I don't understand how the compiler can let you mark your `std::mutex` constructor as `constexpr`: even if you mark `_nonrecursiveMutex<recursive_mutex>` as such, your base class (`recursive_mutex`) isn't, and

>  In a definition of a `constexpr` constructor, each of the parameter types shall be a literal type. In addition, either its function-body shall be `= delete` or `= default` or it shall
satisfy the following constraints: [...]
> - every constructor involved in initializing non-static data members and base class sub-objects shall be a `constexpr` constructor;

OTOH, `recursive_mutex` constructor cannot be made `constexpr`, as

> - the compound-statement of its function-body shall contain only
>     - null statements,
>     - *static_assert-declarations*
>     - `typedef` declarations and alias-declarations that do not define classes or enumerations,
>     - *using-declarations*,
>     - and *using-directives*;

(C++11 §7.1.5 ¶4)

where a call to a function such as `InitializeCriticalSection` clearly isn't admitted. This is confirmed by g++: if I compile a sample program such as

    #include <windows.h>

    struct MyMutex {
        CRITICAL_SECTION cs;
        constexpr MyMutex() {
            InitializeCriticalSection(&cs);
        }

        ~MyMutex() {
            DeleteCriticalSection(&cs);
        }
    };

    struct MyDerivedMutex : MyMutex {
        constexpr MyDerivedMutex() {}
    };

    MyDerivedMutex foo;

    int main() {
        return 0;
    }

I get

```
[mitalia@mitalia ~/scratch]$ /opt/mingw-2017/bin/i686-w64-mingw32-g++ -std=c++11 constexprconstructor.cpp 
constexprconstructor.cpp: In constructor ‘MyMutex::MyMutex()’:
constexprconstructor.cpp:7:5: error: constexpr constructor does not have empty body
     }
     ^
constexprconstructor.cpp: In constructor ‘constexpr MyDerivedMutex::MyDerivedMutex()’:
constexprconstructor.cpp:15:32: error: call to non-constexpr function ‘MyMutex::MyMutex()’
     constexpr MyDerivedMutex() {}
                                ^
```

in C++11 mode, and

```
[mitalia@mitalia ~/scratch]$ /opt/mingw-2017/bin/i686-w64-mingw32-g++ -std=c++14 constexprconstructor.cpp 
constexprconstructor.cpp: In constructor ‘constexpr MyMutex::MyMutex()’:
constexprconstructor.cpp:7:5: error: member ‘MyMutex::cs’ must be initialized by mem-initializer in ‘constexpr’ constructor
     }
     ^
constexprconstructor.cpp:4:22: note: declared here
     CRITICAL_SECTION cs;
                      ^~
```

in C++14 mode.

**Comment by cvtsi2sd** [comment]
That being said, I'd said that then probably the bug is not really in `call_once` (that should implemented as you proposed), but in `mutex`, that should be implemented in some way that allows a `constexpr` constructor. I'd say that probably we should have an `std::atomic_int` besides the `CRITICAL_SECTION` initialized to zero, and defer the creation of `CRITICAL_SECTION` to the first usage (using the `atomic_int` as a flag to check for initialization and as a spinlock).

**Comment by alxvasilev** [comment]
You are right! My knowledge on constexpr was not very solid, as I thought it does not forbid code execution and may be used in a relaxed way to give priority to constexpr code over other non-constexpr static initializations. Obviously wrong. From what I read, MSVC has the same problem with the std::mutex constructor - for the 6+ years of existence, they haven't made it constexpr, so it doesn't comply to the standard. Using an additional flag in std::mutex and deferring its initialization seems the only solution, but it would have a performance penalty.... Maybe we can implement it under an #ifdef, to allow users to choose between performance and standard compliance (which would be necessary only in relatively rare use cases).
Same for once_flag, though, it looks like users may need the constepxr constructor in more cases. So, what do you think about the conditional switch that would enable both mutex and once_flag?

**Comment by cvtsi2sd** [comment]
I think that's it can be a good intermediate position. In that case, we can keep something like your current implementation for `call_once`, and just let the flag affect `std::mutex`.

**Pull request closed without merging**
