### PR TITLE
"Std-like" headers generator

### PR DESCRIPTION
**Pull request by BSG-75**
Sometimes I don't want to modify all my source files to change includes from `#include <header>` to `#include "mingw.header.h"`. So I wrote some simple scripts which will generate header files named in the "standard way", allowing us to keep our `#include`s unchanged, but at the same time, **without making changes to the system headers**.

### How to use
The script used to generate files requires PowerShell. I avoided to some newer features, hoping to make my script compatible with PowerShell 2.0 (which can be installed on Windows XP as well, unfortunately I don't have XP on my PC so I can't test whether my script works on XP or not...)

**Example:**
`generate_std_like_headers.bat -DestinationFolder "some/folder"`
`g++ foo.cpp -o foo.exe -std=c++17 -Wall -Isome/folder`
Several headers (`<thread>`, `<mutex>` etc.) will be generated inside "some/folder", which can then be added to GCC's include path through the `-I` option. User provided include paths have higher priority than the system search paths, so GCC will look for these generated headers instead of real system headers.

The files [tests.cpp](https://github.com/BSG-75/mingw-std-threads/blob/50ce3659cd00fc991d6ddc32370d64c33e9fb0df/tests/tests.cpp#L8) and [CMakeLists.txt](https://github.com/BSG-75/mingw-std-threads/blob/50ce3659cd00fc991d6ddc32370d64c33e9fb0df/tests/CMakeLists.txt#L16) inside `tests` folder have been modified so it can use these new generated files, by passing `-DCMAKE_BUILD_TYPE=StdLikeHeaders` to CMake.

### Additional Options
**Interactive mode**
You can also run `generate_std_like_headers_interactive.bat`, which doesn't need any command line parameters, instead it prompts for user input interactively.

**Manually specifying GCC's path**
You can also manually specify GCC's path (it will be used to search for system headers) by using the `-GccPath` option, for example `generate_std_like_headers.bat -DestinationFolder some\folder -GccPath C:\MinGW-w64\bin\gcc`. When this options is not specified, my script will try to invoke GCC directly (assuming it's inside PATH).

**"Compiler wrapper" batch script**
If you don't want to pass the `-I` option manually to the compiler, you can also use the option `-GenerateCompilerWrapperWithFileName`. It will create a batch script which automatically forwards any argument to `g++.exe`, plus a `-I` option. 

For example:
`generate_std_like_headers.bat -DestinationFolder "some/folder" -GenerateCompilerWrapperWithFileName mingw-std-headers-g++.bat`
Then you can compile with the following command:
`mingw-std-headers-g++ foo.cpp -o foo.exe -std=c++17 -Wall`

### CODE REVIEW

**Comment by nmcclatchey** [comment]
I like the way you think; this is a valuable contribution to the library.

Some thoughts:
- The macro `USE_STD_LIKE_HEADERS` has a fair chance of colliding with macros from other libraries. To reduce odds of a collision, it can be prefaced with the name of the project: `MINGW_STDTHREAD_USE_STD_LIKE_HEADERS`.
- [CMake](https://cmake.org/cmake/help/latest/command/configure_file.html) has a `configure_file` utility, which can be used to create a new file with various tokens replaced. This could be used to replace the bash script (which some users might not be comfortable running, especially because it creates an alias for their compiler...) with a cmake sub-file for inclusion in user's own CMake project. This would provide an alternate approach, for those who wish to make this decision on a project level, rather than on a system level.

**Comment by BSG-75** [comment]
> * The macro `USE_STD_LIKE_HEADERS` has a fair chance of colliding with macros from other libraries. To reduce odds of a collision, it can be prefaced with the name of the project: `MINGW_STDTHREAD_USE_STD_LIKE_HEADERS`.

All right, will update that soon.


> * [CMake](https://cmake.org/cmake/help/latest/command/configure_file.html) has a `configure_file` utility, which can be used to create a new file with various tokens replaced. This could be used to replace the bash script (which some users might not be comfortable running, especially because it creates an alias for their compiler...) with a cmake sub-file for inclusion in user's own CMake project. This would provide an alternate approach, for those who wish to make this decision on a project level, rather than on a system level.

Actually the script won't create an alias for their compiler by default, but only when user specifies explicitly the `-GenerateCompilerWrapperWithFileName` command line option. If the generated alias is not inside PATH then it won't be able to be referenced (directly) from other location.

I'll look into `configure_file` now, will make a commit as soon as I figure out how to parse GCC output from CMake.

**Comment by BSG-75** [comment]
Should we create a project-level CMakeLists.txt (with an option to generate std-like headers)?
Because otherwise it's becoming harder to work with `tests.cpp` if I make the _std-like header generator_'s CMakeLists.txt in another sub directory...

**Comment by BSG-75** [comment]
Made some changes to allow generating headers purely from CMake. it should fully work without any problems now, except that it works only for gcc and clang (or any other compiler that supports `-H` option). 
Actually at the beginning I only considered the case of GCC, since that's the compiler which is normally used with MinGW. Until I saw this [PR](https://github.com/meganz/mingw-std-threads/pull/53), which mentioned clang and "all other popular compilers under Windows"......

Fortunately clang has a similar `-H` option too, which like GCC, outputs the full path of included headers. So this feature can be used with clang as well.
But if we are going to support other compilers such as MSVC (currently generating "std-like" headers is not implemented for MSVC), then the thing becomes more complicated, because it looks like `cl.exe` doesn't provide an option to retrieve full paths of included headers, nor it provides an option to retrieve system header's search paths, and these options are essential for the current approach which consists in including both _standard header_ and _mingw-stdthread's header_ by full path to avoid filename conflicts (if the generated file is named `thread`, and you `#include <thread>` inside this file, and if this generated file is inside the include path, then you won't be able to include the original `thread`, unless you specify its full path)
An alternative approach does exists, we could create an intermediate file first, which includes _standard header_ and _mingw-stdthreads's header_. Then we preprocess it (all compilers supports preprocessing), and use the preprocessed file as the generated header. This approach has the downside of having all macros already expanded during header file generation, and I haven't tried this approach yet.

**Comment by alxvasilev** [comment]
Hi @BSG-75
Thanks for your contribution! One thing - we still need the system <mutex> header, which is included by mingw.mutex.h. Did you test that mingw.mutex.h still works, or am I missing something?

**Comment by nmcclatchey** [comment]
@alxvasilev 
That appears to be covered by [line 60 of CMakeLists.txt](https://github.com/meganz/mingw-std-threads/blob/65c2cd1cefd5b828ed0ca172010df5243aa1a1b2/cmake_stdheaders_generator/CMakeLists.txt#L60). Are you seeing compilation errors?

**Comment by alxvasilev** [comment]
I don't have the possibility to test right now, but I wonder how it can work if inside mingw.mutex.h #include&lt;mutex&gt; forces inclusion of the stub header instead of the needed system one.

**Comment by BSG-75** [comment]
@alxvasilev When any file (regardlessly of user code or headers) includes `<mutex>`, the generated header will be included.
The generated header will in turn include system `mutex` header, this time not by `#include <mutex>`, but by using `#include "{full path to system mutex file}"`. Then `mingw.mutex.h` will also be included by the generated header.

So, system's mutex is already included even before mingw.mutex.h is included.

**Comment by alxvasilev** [comment]
Ok, I saw it now, thanks. Then, I think all looks good. Merging.

**Pull request merged**
