### PR TITLE
improve header generation

### PR DESCRIPTION
**Pull request by oltolm**
makes manual changes to `c++config.h` unnecessary for MinGW-w64 v3.0.0
and above

### CODE REVIEW

**Comment by BSG-75** [comment]
Will look into this tomorrow morning

**Comment by BSG-75** [comment]
Made a quick look, didn't looked into it to deep for now (will do it later), but I think things seems to be good.
Just one question, I'm not very familiar with "non-public" part of standard headers, can we be sure that when using `mingw-std-threads`, _our_ `c++config.h` will always have priority?

I mean let's say some other std headers (let's suppose `<iostream>`, btw it's just an example) included `<bits/foo.h>`, and let's suppose content of `#include <bits/foo.h>` is this:
```c++
#include "./c++config.h"
#include "../mutex"
```

Then IIRC _our_ `bits/c++config.h` won't be included because it doesn't match the search path. And the system's `<mutex>` will have the pthread implementation, which will conflict with our implementation.
Can we be sure this won't happen?

**Comment by oltolm** [comment]
I also thought about this potential problem. I searched in all mingw-w64 GCC headers for `c++config.h`. It is *always* included like this `<bits/c++config.h>`. This shouldn't be a problem in practice and is better than manually editing a global header file anyway in my opinion.

**Comment by BSG-75** [comment]
Then I think we need another dedicated option for cmake (e.g. user can turn the option to `ON` / `OFF`) and a similar dedicated switch in powershell script, so user can opt it in or opt it out. And we'd also need to mention these options in the `README.md`.

**Comment by alxvasilev** [comment]
I also think that we can't rely on the current state of the stdlib internal implementation to guarantee no problem will occur. While editing a global system header may be ugly, it would be more robust.

**Pull request closed without merging**
